### ISSUE TITLE
Segfault when building with debug.

### ISSUE THREAD

**Issue by rnburn** [rnburn/envoy#2]
If a debug version of envoy is built using
```
./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.debug.server_only'
```

Then the program segfaults upon startup. Below's the trace I get from gdb when loading the coredump. It seems that problem has something to do with the initialization of static variables.
(I don't run into the problem when using the release version.)
```
(gdb) bt
#0  tcmalloc::SLL_Next (t=0x1) at src/linked_list.h:45
#1  tcmalloc::SLL_TryPop (rv=<synthetic pointer>, list=0x2b4e140) at src/linked_list.h:69
#2  tcmalloc::ThreadCache::FreeList::TryPop (rv=<synthetic pointer>, this=0x2b4e140) at src/thread_cache.h:220
#3  tcmalloc::ThreadCache::Allocate (cl=10, size=144, this=<optimized out>) at src/thread_cache.h:381
#4  (anonymous namespace)::do_malloc (size=144) at src/tcmalloc.cc:1289
#5  tcmalloc::do_allocate_full<tcmalloc::cpp_throw_oom> (size=144) at src/tcmalloc.cc:1691
#6  tcmalloc::allocate_full_cpp_throw_oom (size=144) at src/tcmalloc.cc:1705
#7  0x0000000000b0f81c in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<spdlog::logger, std::allocator<spdlog::logger>, (__gnu_cxx::_Lock_policy)2> >::allocate (this=0x7ffc7155e896, __n=1) at /usr/include/c++/5/ext/new_allocator.h:104
#8  0x0000000000b0f65d in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<spdlog::logger, std::allocator<spdlog::logger>, (__gnu_cxx::_Lock_policy)2> > >::allocate (__a=..., __n=1) at /usr/include/c++/5/bits/alloc_traits.h:491
#9  0x0000000000b0f316 in std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<spdlog::logger, std::allocator<spdlog::logger>, (__gnu_cxx::_Lock_policy)2> > > (__a=...) at /usr/include/c++/5/bits/allocated_ptr.h:102
#10 0x0000000000b0eee2 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<spdlog::logger, std::allocator<spdlog::logger>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink> >(std::_Sp_make_shared_tag, spdlog::logger*, std::allocator<spdlog::logger> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink>&&) (this=0x7ffc7155ea68, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:615
#11 0x0000000000b0ea41 in std::__shared_ptr<spdlog::logger, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<spdlog::logger>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink> >(std::_Sp_make_shared_tag, std::allocator<spdlog::logger> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink>&&) (
    this=0x7ffc7155ea60, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:1097
#12 0x0000000000b0e6ce in std::shared_ptr<spdlog::logger>::shared_ptr<std::allocator<spdlog::logger>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink> >(std::_Sp_make_shared_tag, std::allocator<spdlog::logger> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink>&&) (this=0x7ffc7155ea60, __tag=...,
    __a=...) at /usr/include/c++/5/bits/shared_ptr.h:319
#13 0x0000000000b0e1cf in std::allocate_shared<spdlog::logger, std::allocator<spdlog::logger>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink> >(std::allocator<spdlog::logger> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink>&&) (__a=...) at /usr/include/c++/5/bits/shared_ptr.h:620
#14 0x0000000000b0db57 in std::make_shared<spdlog::logger, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Envoy::Logger::LockingStderrSink>&&) () at /usr/include/c++/5/bits/shared_ptr.h:636
#15 0x0000000000b0c341 in Envoy::Logger::Logger::Logger (this=0x7ffc7155eb30, name=...) at source/common/common/logger.cc:20
#16 0x0000000000b0c83e in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at source/common/common/logger.cc:17
#17 0x0000000000b0d341 in _GLOBAL__sub_I__ZN5Envoy6Logger8Registry12all_loggers_E () at source/common/common/logger.cc:45
#18 0x0000000000bd4dad in __libc_csu_init ()
#19 0x00007fb489e5c7bf in __libc_start_main (main=0x41a577 <main(int, char**)>, argc=1, argv=0x7ffc7155f028, init=0xbd4d60 <__libc_csu_init>,
---Type <return> to continue, or q <return> to quit---
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc7155f018) at ../csu/libc-start.c:247
#20 0x0000000000418f79 in _start ()
```

**Comment by rnburn** [comment]
I created a [branch](https://github.com/rnburn/lightstep-tracer-cpp-1/tree/logging) of the LightStep tracer that has all the logging commented out and the spdlog dependency removed. I was a able to do the debug build of envoy against this without the segfaulting, so it looks like the problem has something to do with the static variables in the spdlog library.

**Comment by rnburn** [comment]
Fixed by removing spdlog from lightstep.
